version: '3'
services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db:
    driver: local